spring:
  application:
    name: anime-service
  threads:
    virtual:
      enabled: true
  devtools:
    restart:
      enabled: false
server:
  servlet:
    context-path: /
  error:
    include-stacktrace: on_param
  tomcat:
    threads:
      max: 20